### ISSUE TITLE
[Node.js Bootcamp] Project 0: Proxy Server - Ready for Review #1

### ISSUE THREAD

**Issue by jxhangithub** [jxhangithub/proxy-server#1]
My app is complete. /cc @codepathreview and @codepath

I have a question about log to file. I tried exact steps and code as the video, but it seems the log still use process.stdout not to a file. Could you please let me know what I need to fix? Thanks.

I did experience one issue when install babel, detailed message as below:

$ npm install -g babel

> fsevents@0.3.5 install /Users/jhan9/.npmprefix/lib/node_modules/babel/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/Users/jhan9/.npmprefix/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:166:7)
gyp ERR! stack     at Request.onRequestResponse (/Users/jhan9/.npmprefix/lib/node_modules/npm/node_modules/request/request.js:1156:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:166:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:412:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:302:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "/usr/local/bin/iojs" "/Users/jhan9/.npmprefix/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jhan9/.npmprefix/lib/node_modules/babel/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v1.8.1
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing fsevents@0.3.5
/Users/jhan9/.npmprefix/bin/babel -> /Users/jhan9/.npmprefix/lib/node_modules/babel/bin/babel/index.js
/Users/jhan9/.npmprefix/bin/babel-external-helpers -> /Users/jhan9/.npmprefix/lib/node_modules/babel/bin/babel-external-helpers
/Users/jhan9/.npmprefix/bin/babel-node -> /Users/jhan9/.npmprefix/lib/node_modules/babel/bin/babel-node
babel@5.1.11 /Users/jhan9/.npmprefix/lib/node_modules/babel
├── path-is-absolute@1.0.0
├── fs-readdir-recursive@0.1.1
├── convert-source-map@0.5.1
├── commander@2.8.0 (graceful-readlink@1.0.1)
├── source-map@0.4.2 (amdefine@0.1.0)
{
├── output-file-sync@1.1.0 (xtend@4.0.0, mkdirp@0.5.0)
├── chokidar@1.0.1 (is-glob@1.1.3, arrify@1.0.0, glob-parent@1.2.0, async-each@0.1.6, is-binary-path@1.0.0, readdirp@1.3.0, anymatch@1.2.1)
├── lodash@3.7.0
└── babel-core@5.1.11 (slash@1.0.0, trim-right@1.0.0, to-fast-properties@1.0.1, shebang-regex@1.0.0, leven@1.0.1, strip-json-comments@1.0.2, user-home@1.1.1, private@0.1.6, globals@6.4.1, estraverse@3.1.0, esutils@2.0.2, convert-source-map@1.1.0, js-tokens@1.0.0, debug@2.1.3, ast-types@0.7.6, line-numbers@0.2.0, is-integer@1.0.4, detect-indent@3.0.1, chalk@1.0.0, minimatch@2.0.4, repeating@1.1.2, source-map-support@0.2.10, regexpu@1.1.2, regenerator@0.8.22, core-js@0.8.4)

**Comment by CrabDude** [comment]
Is the issue repeatable? It looks like it may just have been a temporary server issue. Can you try reinstalling?

**Comment by CrabDude** [comment]
@jxhangithub There's an argument collision issue with using `nodemon` and `babel-node`. I've updated the [Setup Guide's nodemon section](http://guides.codepath.com/nodejs/Setup#install-the-nodemon-daemon) but the show of it is...

Use this:

``` bash
nodemon --exec babel-node -- --optional strict --stage 1 -- index.js --foo=bar
```

Instead of this:

``` bash
nodemon --exec babel-node -- --optional strict --stage 1 index.js --foo=bar
```

Note the additional `--`.

For convenience, you can alias this:

``` bash
bodemonalias="alias bodemon='nodemon --exec babel-node -- --optional strict --stage 1 -- '"
echo $bodemonalias >> ~/.bash_profile                # Persist alias
bodemon somefile.js
```

**Comment by codepathreview** [comment]
Looks good! Hope you found this first project useful as a brief introduction or review of Node.js.

This was intended in part to give you a flavor for the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a code review for each submitted project once the bootcamp starts.

The next step is to continue working on extensions to your Node.js server. We will be confirming with you soon if you are going to be a part of the first Node.js bootcamp at Walmart Labs. Please email us at nodejs@codepath.com if you have any questions!

**Comment by codepathreview** [comment]
@jxhangithub Please make sure to include a proper README from next time. You can refer this sample [README](https://github.com/CrabDude/nodejs-proxy-demo/blob/master/README.md)

**Comment by jxhangithub** [comment]
Hello Adam,

I have tried this in two or three different days multiple times. It can be
repeated by my computer. I will definitely try it again today with the
latest setup guide.

Have a great weekend!

Thanks.

Jiaxin Han

**Comment by CrabDude** [comment]
It looks like your issue is related to io.js and node-gyp, see [here](https://github.com/strongloop/fsevents/issues/55) caused by upgrading to latest npm.

Try the following:

``` bash
npm install -g npm@2.8.3
```

**Comment by jxhangithub** [comment]
I tried two approach for this, but no luck

$ npm install -g npm@2.8.3
/Users/jhan9/.npmprefix/bin/npm -> /Users/jhan9/.npmprefix/lib/node_modules/npm/bin/npm-cli.js
npm@2.8.3 /Users/jhan9/.npmprefix/lib/node_modules/npm
$ npm install -g babel

> fsevents@0.3.5 install /Users/jhan9/.npmprefix/lib/node_modules/babel/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: 404 status code downloading tarball
gyp ERR! stack     at Request.<anonymous> (/Users/jhan9/.npmprefix/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:246:14)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:166:7)
gyp ERR! stack     at Request.onRequestResponse (/Users/jhan9/.npmprefix/lib/node_modules/npm/node_modules/request/request.js:1156:10)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at ClientRequest.emit (events.js:166:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:412:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:88:23)
gyp ERR! stack     at Socket.socketOnData (_http_client.js:302:20)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! System Darwin 13.4.0
gyp ERR! command "/usr/local/bin/iojs" "/Users/jhan9/.npmprefix/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/jhan9/.npmprefix/lib/node_modules/babel/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v1.8.1
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm WARN optional dep failed, continuing fsevents@0.3.5
/Users/jhan9/.npmprefix/bin/babel -> /Users/jhan9/.npmprefix/lib/node_modules/babel/bin/babel/index.js
/Users/jhan9/.npmprefix/bin/babel-external-helpers -> /Users/jhan9/.npmprefix/lib/node_modules/babel/bin/babel-external-helpers
/Users/jhan9/.npmprefix/bin/babel-node -> /Users/jhan9/.npmprefix/lib/node_modules/babel/bin/babel-node
babel@5.1.13 /Users/jhan9/.npmprefix/lib/node_modules/babel
├── path-is-absolute@1.0.0
├── fs-readdir-recursive@0.1.1
├── convert-source-map@1.1.0
├── commander@2.8.1 (graceful-readlink@1.0.1)
├── output-file-sync@1.1.0 (xtend@4.0.0, mkdirp@0.5.0)
├── source-map@0.4.2 (amdefine@0.1.0)
├── chokidar@1.0.1 (arrify@1.0.0, is-glob@1.1.3, async-each@0.1.6, glob-parent@1.2.0, is-binary-path@1.0.0, readdirp@1.3.0, anymatch@1.3.0)
├── lodash@3.7.0
└── babel-core@5.1.13 (slash@1.0.0, to-fast-properties@1.0.1, shebang-regex@1.0.0, leven@1.0.1, trim-right@1.0.0, strip-json-comments@1.0.2, user-home@1.1.1, globals@6.4.1, private@0.1.6, estraverse@3.1.0, esutils@2.0.2, js-tokens@1.0.0, debug@2.1.3, is-integer@1.0.4, line-numbers@0.2.0, ast-types@0.7.6, detect-indent@3.0.1, chalk@1.0.0, repeating@1.1.2, minimatch@2.0.4, source-map-support@0.2.10, regexpu@1.1.2, regenerator@0.8.22, core-js@0.9.4)

# 

$ export npm_config_nodedir=/Users/jhan9/.nvm/versions/io.js/v1.8.1/bin/npm install
$ vi ~/.bash_profile
9$ npm install -g babel
npm ERR! not a package /Users/jhan9/.nvm/versions/io.js/v1.8.1/bin/babel
npm ERR! addLocal Could not install /Users/jhan9/.nvm/versions/io.js/v1.8.1/bin/babel
npm ERR! Darwin 13.4.0
npm ERR! argv "/Users/jhan9/.nvm/versions/io.js/v1.8.1/bin/iojs" "/Users/jhan9/.npmprefix/bin/npm" "install" "-g" "babel"
npm ERR! node v1.8.1
npm ERR! npm  v2.8.3
npm ERR! path /var/folders/_j/tflcvrr5167c0cz0v787pys1_79tdl/T/npm-59768-ef5a5ef9/unpack-31f017cbdf46/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/var/folders/_j/tflcvrr5167c0cz0v787pys1_79tdl/T/npm-59768-ef5a5ef9/unpack-31f017cbdf46/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/jhan9/.nvm/versions/io.js/v1.8.1/bin/npm-debug.log

**Comment by CrabDude** [comment]
Sorry you're having so much trouble. I'll put together a list of recommendations today and worst case, we can schedule a Skype or meet before or after class to sort this out. 

For now, since you have io.js installed, trying using node@v0.12 or v0.10. Both should work just fine.

**Comment by jxhangithub** [comment]
Hello Adam,

My proxy server works fine now. Just the installation has some errors
for babel, does that mean this is ok? Another question, how can I setup to
use node@v0.12 or v0.10?

Thanks.

Jiaxin

**Comment by CrabDude** [comment]
If you followed the setup and used [`nvm`](https://github.com/creationix/nvm) to install, then:

``` bash
nvm install v0.12
nvm alias default 0.12
```

Otherwise you can install directly from [nodejs.org](http://nodejs.org)

**Comment by jxhangithub** [comment]
Hello Adam,

I use the first command then install babel, it is successful. Thanks for
your help!

$ nvm install v0.12
########################################################################
100.0% Now using node v0.12.2
$ npm install -g babel > fsevents@0.3.5 install
/Users/jhan9/.npmprefix/lib/node_modules/babel/node_modules/chokidar/node_modules/fsevents

> node-gyp rebuild xcode-select: error: tool 'xcodebuild' requires Xcode,
> but active developer directory '/Library/Developer/CommandLineTools' is a
> command line tools instance xcode-select: error: tool 'xcodebuild' requires
> Xcode, but active developer directory '/Library/Developer/CommandLineTools'
> is a command line tools instance SOLINK_MODULE(target) Release/.node
> SOLINK_MODULE(target) Release/.node: Finished CXX(target)
> Release/obj.target/fse/fsevents.o SOLINK_MODULE(target) Release/fse.node
> SOLINK_MODULE(target) Release/fse.node: Finished
> /Users/jhan9/.npmprefix/bin/babel ->
> /Users/jhan9/.npmprefix/lib/node_modules/babel/bin/babel/index.js
> /Users/jhan9/.npmprefix/bin/babel-external-helpers ->
> /Users/jhan9/.npmprefix/lib/node_modules/babel/bin/babel-external-helpers
> /Users/jhan9/.npmprefix/bin/babel-node ->
> /Users/jhan9/.npmprefix/lib/node_modules/babel/bin/babel-node babel@5.1.13
> /Users/jhan9/.npmprefix/lib/node_modules/babel ├──
> fs-readdir-recursive@0.1.1 ├── path-is-absolute@1.0.0 ├──
> convert-source-map@1.1.0 ├── commander@2.8.1 (graceful-readlink@1.0.1) ├──
> source-map@0.4.2 (amdefine@0.1.0) ├── output-file-sync@1.1.0 (xtend@4.0.0,
> mkdirp@0.5.0) ├── lodash@3.7.0 ├── babel-core@5.1.13 (slash@1.0.0,
> shebang-regex@1.0.0, trim-right@1.0.0, to-fast-properties@1.0.1, leven@1.0.1,
> user-home@1.1.1, strip-json-comments@1.0.2, globals@6.4.1, private@0.1.6,
> estraverse@3.1.0, esutils@2.0.2, debug@2.1.3, js-tokens@1.0.0,
> is-integer@1.0.4, line-numbers@0.2.0, ast-types@0.7.6, detect-indent@3.0.1,
> chalk@1.0.0, repeating@1.1.2, minimatch@2.0.4, source-map-support@0.2.10,
> regexpu@1.1.2, regenerator@0.8.22, core-js@0.9.4) └── chokidar@1.0.1
> (arrify@1.0.0, is-glob@1.1.3, glob-parent@1.2.0, async-each@0.1.6,
> is-binary-path@1.0.0, readdirp@1.3.0, anymatch@1.3.0, fsevents@0.3.5)
